version: "2"
services:
  bin-collections-notifier:
    container_name: bin-collections-notifier
    build: .
    environment:
      - API_URL=https://vigilant-walker-306711.nw.r.appspot.com
      - MONGO_URI=${MONGO_URI}
      - TWILIO_SID=${TWILIO_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_FROM_NUMBER=${TWILIO_FROM_NUMBER}
      - SUBSCRIPTIONS_POLL_CRON="* 55 * * *"
    ports:
      - "3000:3000"
    links:
      - redis
  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ./redis-data:/data/redis