version: "2"
services:
  bin-collections-notifier:
    container_name: bin-collections-notifier
    build: .
    environment:
      - API_URL=https://vigilant-walker-306711.nw.r.appspot.com/
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - SUBSCRIPTIONS_POLL_CRON="55 18 * * *"
    ports:
      - "3000:3000"
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    # command: ["--auth"]
    ports:
      - "27017:27017"
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis
    volumes:
      - ./redis-data:/data/redis